name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build App
        run: |
          nuitka --lto=yes --windows-console-mode=disable --enable-plugin=pyside6 --remove-output --follow-imports --output-dir=dist/ --include-data-files=./zh_CN.qm=./zh_CN.qm --mode=app ./main.py


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ runner.os }} Build
          path: |  # match what's created for the 3 OSes
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
