name: Build macOS App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip -r requirements.txt
      - name: Build App
        run: |
          nuitka --lto=yes --windows-console-mode=disable --standalone --enable-plugin=pyside6 --remove-output --follow-imports --output-dir=build/ --include-data-files=./zh_CN.qm=./zh_CN.qm .\main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: myapp-mac
          path: dist/
